import Head from "next/head";
import Nav from "~/components/nav";
import SidePanel from "~/components/sidePanel";
import TopStreamer from "~/components/topStreamer";
import RunnerUp from "~/components/runnerUp";
// import { api } from "~/utils/api";

export default function Home() {
  // const { data } = api.stream.hello.useQuery();
  // if (!data) return <div>no data</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center overflow-auto bg-gradient-to-b from-black to-[#18181B] [&::-webkit-scrollbar]:hidden">
        <Nav />
        <div className="flex h-[calc(100vh-48px)] w-full flex-col text-white md:flex-row">
          <SidePanel />
          <div className="flex w-full flex-col items-center text-center md:pt-2">
            <TopStreamer />
            <RunnerUp />
          </div>
        </div>
      </main>
    </>
  );
}
